---
title: "Modelling the effects of public health interventions on COVID-19 transmission using R - part 2"
description: |
  This is the secondof several posts which examine the effect of various public health interventions on the local epidemic spread of COVID-19 infection using stochastic compartmental models implemented by the `EpiModel` library for R. In this post we extend the ICM SIR model provided by `EpiModel` in various ways to improve its verisimilitude.
categories:
  - R
  - "COVID-19"
author:
  - name: Tim Churches 
    affiliation: South Western Sydney Clinical School, UNSW Medicine & Ingham Institute of Applied Medical Research, Liverpool, Sydney, Australia
    affiliation_url: https://swscs.med.unsw.edu.au
creative_commons: CC BY-SA
date: 03-11-2020
base_url: https://timchurches.github.io/blog/
slug: churches2020modellingcovid19rpart2
twitter:
  creator: "@timchurches"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
draft: true
repository_url: https://github.com/timchurches/blog/tree/master/_posts/2020-03-11-modelling-the-effects-of-public-health-interventions-on-covid-19-transmission-part-2
bibliography: churches2020modellingcovid19rpart2_references.bib
---


```{r setup, include=FALSE, eval=TRUE}
version_date <- lubridate::ymd("2020-03-11")

knitr::opts_chunk$set(echo = FALSE, cache=FALSE, eval=TRUE,
                      tidy.opts=list(width.cutoff=60),
                      tidy=TRUE)
library(tidyverse)
library(magrittr)
library(lubridate)
library(stringr)
library(tibble)
library(broom)
library(ggplot2)
library(ggthemes)
library(gt)
library(knitr)

```

# Introduction

# Existing model

```{r, echo=TRUE, eval=TRUE}
# Load EpiModel
suppressMessages(library(EpiModel))

src_path <- "./_posts/2020-03-11-modelling-the-effects-of-public-health-interventions-on-covid-19-transmission-part-2/"
  
source(paste(src_path, "_icm.mod.init.seir.R", sep=""))
source(paste(src_path, "_icm.mod.status.seir.R", sep=""))
source(paste(src_path, "_icm.mod.vital.seir.R", sep=""))
source(paste(src_path, "_icm.control.seir.R", sep=""))
source(paste(src_path, "_icm.utils.seir.R", sep=""))

control <- control.icm(type = "SIR", nsteps = 365, nsims = 10)
init <- init.icm(s.num = 997, i.num = 3, r.num = 0)
param <-  param.icm(inf.prob = 0.05, 
                    act.rate = 10,
                    rec.rate = 1/20,
                    a.rate = (10.5/365)/1000, 
                    ds.rate = (7/365)/1000, 
                    di.rate = (3.5/365)/1000,
                    dr.rate = (7/365)/1000)
sir_sim <- icm(param, init, control)

sir_sim_df <- as.data.frame(sir_sim, out="mean")
```

# SEIR model

```{r, echo=TRUE, eval=TRUE}

control <- control.icm(type = "SEIR", 
                       nsteps = 365, 
                       nsims = 10,
                       prog.rand = TRUE,
                       infection.FUN = infection.seir.icm,
                       recovery.FUN = progress.seir.icm)

init <- init.icm(s.num = 997, i.num = 3, e.num=0, r.num = 0)
param <-  param.icm(inf.prob = 0.05, 
                    act.rate = 10,
                    prog.rate = 1/10,
                    rec.rate = 1/20,
                    a.rate = (10.5/365)/1000, 
                    ds.rate = (7/365)/1000, 
                    de.rate = (7/365)/1000, 
                    di.rate = (3.5/365)/1000,
                    dr.rate = (7/365)/1000)
seir_sim <- icm(param, init, control)

seir_sim_df <- as.data.frame(seir_sim, out="mean")

```

```{r, echo=TRUE, eval=TRUE}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  filter(time <= 200) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line() +
    facet_grid(model ~ .)
```

```{r, echo=TRUE, eval=FALSE}
seir_sim_df %>%
  select(time, se.flow, ei.flow, ir.flow) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, si.flow, ir.flow) %>%
              mutate(model = "SIR")) %>%
  filter(time <= 200) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line() +
    facet_grid(model ~ .)
```

## SEIR model with gamma progress probs

```{r, echo=TRUE, eval=FALSE}
source(paste(src_path, "_icm.mod.init.seiqhr.R", sep=""))
source(paste(src_path, "_icm.mod.status.seiqhr.R", sep=""))
source(paste(src_path, "_icm.mod.vital.seiqhr.R", sep=""))
source(paste(src_path, "_icm.control.seiqhr.R", sep=""))
source(paste(src_path, "_icm.utils.seiqhr.R", sep=""))
```

```{r, echo=TRUE, eval=TRUE}
source(paste(src_path, "_icm.mod.init.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.mod.status.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.mod.vital.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.control.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.utils.seiqhrf.R", sep=""))
```

```{r, echo=TRUE, eval=TRUE, tidy=FALSE}

control <- control.icm(type = "SEIR", 
                       nsteps = 365, 
                       nsims = 10,
                       prog.rand = FALSE,
#                       infection.FUN = infection.seiqhr.icm,
#                       recovery.FUN = progress.seiqhr.icm,
#                       departures.FUN = departures.seiqhr.icm,
#                       get_prev.FUN = get_prev.seiqhr.icm)
                       infection.FUN = infection.seiqhrf.icm,
                       recovery.FUN = progress.seiqhrf.icm,
                       departures.FUN = departures.seiqhrf.icm,
                       get_prev.FUN = get_prev.seiqhrf.icm)

init <- init.icm(s.num = 997, i.num = 3, e.num=0, r.num = 0)
param <-  param.icm(inf.prob.i = 0.05, 
                    act.rate.i = 10,
                    prog.rate = 1/10,
                    prog.dist.mu = 5,
                    prog.dist.sigma = 2.4,
                    rec.rate = 1/20,
                    a.rate = (10.5/365)/1000, 
                    ds.rate = (7/365)/1000, 
                    de.rate = (7/365)/1000, 
                    di.rate = (3.5/365)/1000,
                    dr.rate = (7/365)/1000)
gamma_seir_sim <- icm(param, init, control)

gamma_seir_sim_df <- as.data.frame(gamma_seir_sim, out="mean")
```

```{r, echo=TRUE, eval=TRUE}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  bind_rows(gamma_seir_sim_df %>%
              select(time, s.num, e.num, i.num, r.num) %>%
              mutate(model = "gamma SEIR")) %>%
  filter(time <= 100) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line() +
    facet_grid(model ~ .)
```

## SEIQHR model with gamma progress probs

```{r, echo=TRUE, eval=TRUE}

control <- control.icm(type = "SEIQHR", 
                       nsteps = 365, 
                       nsims = 10,
                       prog.rand = FALSE,
                       infection.FUN = infection.seiqhrf.icm,
                       recovery.FUN = progress.seiqhrf.icm,
                       departures.FUN = departures.seiqhrf.icm,
                       get_prev.FUN = get_prev.seiqhrf.icm)

init <- init.icm(s.num = 997, i.num = 3, e.num=0, q.num=0, h.num=0, r.num = 0)
param <-  param.icm(inf.prob.i = 0.05, 
                    act.rate.i = 10,
                    inf.prob.q = 0.05, 
                    act.rate.q = 5,                    
                    quar.rate = 1/10,
                    hosp.rate = 1/50,
                    disch.rate = 1/8,
                    prog.rate = 1/10,
                    prog.dist.mu = 5,
                    prog.dist.sigma = 2.4,
                    rec.rate = 1/20,
                    a.rate = (10.5/365)/1000, 
                    ds.rate = (7/365)/1000, 
                    de.rate = (7/365)/1000, 
                    di.rate = (7/365)/1000,
                    dq.rate = (7/365)/1000,
                    dh.rate = (20/365)/1000,
                    dr.rate = (7/365)/1000)
seiqhr_sim <- icm(param, init, control)

seiqhr_sim_df <- as.data.frame(seiqhr_sim, out="mean")
```

```{r, echo=TRUE, eval=TRUE, fig.height=12, fig.width=10}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  bind_rows(gamma_seir_sim_df %>%
              select(time, s.num, e.num, i.num, r.num) %>%
              mutate(model = "gamma SEIR")) %>%
  bind_rows(seiqhr_sim_df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, dh.flow) %>%
              mutate(model = "SEIQHR")) %>%
  filter(time <= 100) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.4) +
    facet_grid(model ~ .) +
    scale_colour_brewer(type="div") +
    theme_minimal()
```

```{r, echo=TRUE, eval=TRUE, fig.height=12, fig.width=10}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  bind_rows(gamma_seir_sim_df %>%
              select(time, s.num, e.num, i.num, r.num) %>%
              mutate(model = "gamma SEIR")) %>%
  bind_rows(seiqhr_sim_df %>%
              select(time, s.num, e.num, i.num, q.num,
                     h.num, r.num, dh.flow) %>%
              mutate(model = "SEIQHR")) %>%
  filter(time <= 100) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  filter(compartment %in% c("e.num","i.num",
                            "q.num","h.num",
                            "dh.flow")) %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.4) +
    facet_grid(model ~ ., scales="free_y") +
    scale_colour_brewer(type="div") +
    theme_minimal()
```

## SEIQHRF model with gamma progress and recovery probs

```{r, echo=TRUE, eval=TRUE}
source(paste(src_path, "_icm.mod.init.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.mod.status.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.mod.vital.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.control.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.utils.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.saveout.seiqhrf.R", sep=""))
source(paste(src_path, "_icm.icm.seiqhrf.R", sep=""))
```

```{r, echo=TRUE, eval=TRUE}
# function to set-up and run the baseline simulations
simulate <- function(# control.icm params
                     type = "SEIQHRF", 
                     nsteps = 365, 
                     nsims = 10,
                     prog.rand = FALSE,
                     rec.rand = FALSE,
                     fat.rand = FALSE,
                     quar.rand = TRUE,
                     hosp.rand = FALSE,
                     disch.rand = TRUE,
                     infection.FUN = infection.seiqhrf.icm,
                     recovery.FUN = progress.seiqhrf.icm,
                     departures.FUN = departures.seiqhrf.icm,
                     arrivals.FUN = arrivals.seiqhrf.icm,
                     get_prev.FUN = get_prev.seiqhrf.icm,
                     # init.icm params
                     s.num = 997,
                     e.num=0,
                     i.num = 3,
                     q.num=0,
                     h.num=0,
                     r.num = 0,
                     f.num = 0,
                     # param.icm params
                     inf.prob.i = 0.05, 
                     act.rate.i = 10,
                     inf.prob.q = 0.05, 
                     act.rate.q = 8,                    
                     quar.rate = 0, # 1/3
                     hosp.rate = 1/50,
                     disch.rate = 1/12,
                     prog.rate = 1/10,
                     prog.dist.mu = 8.0,
                     prog.dist.sigma = 3,
                     rec.rate = 1/20,
                     rec.dist.mu = 22.0,
                     rec.dist.sigma = 6.0,
                     fat.rate.base = 1/100,
                     hosp.cap = 20,
                     fat.rate.overcap = 1/50,
                     fat.tcoeff = 0.5,
                     vital = TRUE,
                     a.rate = (10.5/365)/1000, 
                     ds.rate = (7/365)/1000, 
                     de.rate = (7/365)/1000, 
                     di.rate = (7/365)/1000,
                     dq.rate = (7/365)/1000,
                     dh.rate = (20/365)/1000,
                     dr.rate = (7/365)/1000,
                     out="mean"
                    ) {

  control <- control.icm(type = type, 
                         nsteps = nsteps, 
                         nsims = nsims,
                         prog.rand = prog.rand,
                         rec.rand = rec.rand,
                         infection.FUN = infection.FUN,
                         recovery.FUN = recovery.FUN,
                         departures.FUN = departures.FUN,
                         get_prev.FUN = get_prev.FUN)

  init <- init.icm(s.num = s.num,
                   e.num = e.num,
                   i.num = i.num,
                   q.num = q.num,
                   h.num = h.num,
                   r.num = r.num,
                   f.num = f.num)

  param <-  param.icm(inf.prob.i = inf.prob.i, 
                      act.rate.i = act.rate.i,
                      inf.prob.q = inf.prob.q, 
                      act.rate.q = act.rate.q,                    
                      quar.rate = quar.rate,
                      hosp.rate = hosp.rate,
                      disch.rate = disch.rate,
                      prog.rate = prog.rate,
                      prog.dist.mu = prog.dist.mu,
                      prog.dist.sigma = prog.dist.sigma,
                      rec.rate = rec.rate,
                      rec.dist.mu = rec.dist.mu,
                      rec.dist.sigma = rec.dist.sigma,
                      fat.rate.base = fat.rate.base,
                      hosp.cap = hosp.cap,
                      fat.rate.overcap = fat.rate.overcap,
                      fat.tcoeff = fat.tcoeff,
                      vital = vital,
                      a.rate = a.rate, 
                      ds.rate = ds.rate, 
                      de.rate = de.rate, 
                      di.rate = di.rate,
                      dq.rate = dq.rate,
                      dh.rate = dh.rate,
                      dr.rate = dr.rate)

  sim <- icm.seiqhrf(param, init, control)
  sim_df <- as.data.frame(sim, out=out)

  return(list(sim=sim, df=sim_df))
}
```

```{r, echo=TRUE, eval=TRUE}
seiqhrf_sim <- simulate()
```

```{r, echo=TRUE, eval=TRUE}
sim <- seiqhrf_sim$sim

for (s in 1:sim$control$nsims) {
  if (s == 1) {
    times <- sim$times[[paste("sim",s,sep="")]]
    times <- times %>% mutate(s=s)
  } else {
    times <- times %>%
      bind_rows(sim$times[[paste("sim",s,sep="")]] %>%
                  mutate(s=s))
  }
}

times <- times %>%
          mutate(infTime=ifelse(infTime <0, -5, infTime),
                 expTime=ifelse(expTime <0, -5, expTime)) %>%
          mutate(incubation_period = infTime - expTime,
                 illness_duration = recovTime - expTime,
                 hosp_los = dischTime - hospTime,
                 quarantine_delay = quarTime - infTime,
                 survival_time = fatTime - infTime)
```

```{r, echo=TRUE, eval=TRUE}
times %>%
  ggplot(aes(x=incubation_period)) +
    geom_histogram() +
    labs(title="Incubations period")
```

```{r, echo=TRUE, eval=TRUE}
times %>%
  ggplot(aes(x=illness_duration)) +
    geom_histogram(bins=24) +
    labs(title="Illness_duration")
```

```{r, echo=TRUE, eval=TRUE}
times %>%
  ggplot(aes(x=hosp_los)) +
    geom_histogram() +
    labs(title="Duration of need for hospitalisation")
```

```{r, echo=TRUE, eval=TRUE}
times %>%
  ggplot(aes(x=quarantine_delay)) +
    geom_histogram() +
    labs(title="Delay to start of quarantine")
```

```{r, echo=TRUE, eval=TRUE}
times %>%
  filter(survival_time <= 25) %>%
  ggplot(aes(x=survival_time)) +
    geom_histogram() +
    labs(title="Survival time in case fatalities")
```

```{r, echo=TRUE, eval=TRUE, fig.height=12, fig.width=10}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  bind_rows(gamma_seir_sim_df %>%
              select(time, s.num, e.num, i.num, r.num) %>%
              mutate(model = "SEIR")) %>%
  bind_rows(seiqhr_sim_df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num) %>%
              mutate(model = "SEIQHR")) %>%
  bind_rows(seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "SEIQHRF")) %>%
  filter(time <= 100) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.7) +
    facet_grid(model ~ .) +
    scale_colour_brewer(type="div") +
    theme_dark()
```

```{r, echo=TRUE, eval=TRUE, fig.height=12, fig.width=10}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  bind_rows(gamma_seir_sim_df %>%
              select(time, s.num, e.num, i.num, r.num) %>%
              mutate(model = "gamma SEIR")) %>%
  bind_rows(seiqhr_sim_df %>%
              select(time, s.num, e.num, i.num, q.num,
                     h.num, r.num, dh.flow) %>%
              mutate(model = "SEIQHR")) %>%
  bind_rows(seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num,
                     h.num, r.num, f.num) %>%
              mutate(model = "SEIQHRF")) %>%
  filter(time <= 100) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  filter(compartment %in% c("e.num","i.num",
                            "q.num","h.num",
                            "f.num")) %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.7) +
    facet_grid(model ~ ., scales="free_y") +
    scale_colour_brewer(type="div") +
    theme_dark()
```

## comparing SEIQHRF models - fixed vs time-variant act rates and inf probs


```{r, echo=TRUE, eval=TRUE}
t30_act_rate_seiqhrf_sim <- simulate(act.rate.i = c(rep(10,30), rep(5, 335)))

t30_inf_prob_seiqhrf_sim <- simulate(inf.prob.i = c(rep(0.05,30), rep(0.025, 335)))

t30_both_seiqhrf_sim <- simulate(inf.prob.i = c(rep(0.05,30), rep(0.025, 335)),
                                    act.rate.i = c(rep(10,30), rep(5, 335)))

t30_quar_inc_seiqhrf_sim <- simulate(quar.rate = c(rep(1/10,30), rep(1/3, 335)))

t30_disch_inc_seiqhrf_sim <- simulate(disch.rate = c(rep(1/8,30), rep(1/4, 335)))

t15_act_rate_seiqhrf_sim <- simulate(act.rate.i = c(rep(10,15), rep(5, 350)))

t15_inf_prob_seiqhrf_sim <- simulate(inf.prob.i = c(rep(0.05,15), rep(0.025, 350)))

t15_both_seiqhrf_sim <- simulate(inf.prob.i = c(rep(0.05,15), rep(0.025, 350)), 
                                    act.rate.i = c(rep(10,15), rep(5, 350)))
```

```{r, echo=TRUE, eval=TRUE, fig.height=12, fig.width=6}
seiqhrf_sim$df %>%
  select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "Fixed params") %>%
  bind_rows(t30_inf_prob_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=30 inf prob")) %>%
  bind_rows(t30_act_rate_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=30 act rate")) %>%
  bind_rows(t30_both_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=30 both")) %>%
  bind_rows(t30_quar_inc_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=30 incr quar rate")) %>%
  bind_rows(t30_disch_inc_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=30 incr disch rate")) %>%
  bind_rows(t15_act_rate_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=15 act rate")) %>%
  bind_rows(t15_inf_prob_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=15 inf prob")) %>%
  bind_rows(t15_both_seiqhrf_sim$df %>%
              select(time, s.num, e.num, i.num, q.num, 
                     h.num, r.num, f.num) %>%
              mutate(model = "t=15 both")) %>%
  filter(time <= 200) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  filter(compartment %in% c("e.num","i.num",
                            "q.num","h.num",
                            "f.num")) -> plot_df

plot_df %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.4) +
    facet_grid(model ~ .) +
    scale_colour_viridis_d() +
    theme_minimal()
```

```{r, echo=TRUE, eval=TRUE, fig.height=12, fig.width=6}
plot_df %>%
  filter(compartment %in% c("h.num",
                            "f.num")) %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.4) +
    facet_grid(model ~ .) +
    scale_colour_viridis_d() +
    theme_dark()
```

Up to here

```{r, echo=TRUE, eval=FALSE, fig.height=12, fig.width=10}
seir_sim_df %>%
  select(time, s.num, e.num, i.num, r.num) %>%
  mutate(model = "SEIR") %>%
  bind_rows(sir_sim_df %>%
              select(time, s.num, i.num, r.num) %>%
              mutate(model = "SIR")) %>%
  bind_rows(gamma_seir_sim_df %>%
              select(time, s.num, e.num, i.num, r.num) %>%
              mutate(model = "gamma SEIR")) %>%
  bind_rows(seiqhr_sim_df %>%
              select(time, s.num, e.num, i.num, q.num,
                     h.num, r.num, dh.flow) %>%
              mutate(model = "SEIQHR")) %>%
  bind_rows(seiqhrf_sim_df %>%
              select(time, s.num, e.num, i.num, q.num,
                     h.num, r.num, f.num) %>%
              mutate(model = "SEIQHRF")) %>%
  filter(time <= 100) %>%
  pivot_longer(-c(time, model),
               names_to="compartment",
               values_to="count") %>%
  filter(compartment %in% c("e.num","i.num",
                            "q.num","h.num",
                            "f.num")) %>%
  ggplot(aes(x=time, y=count, colour=compartment)) +
    geom_line(size=2, alpha=0.4) +
    facet_grid(model ~ ., scales="free_y") +
    scale_colour_brewer(type="div") +
    theme_minimal()
```

```{r}
library(DiagrammeR)

grViz("
digraph SEIQHRF {

  # a 'graph' statement
  graph [overlap = false, fontsize = 10] #, rankdir = LR]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica]
  S[label='Susceptible'];
  E[label='Infected,\nnot infectious'];
  I[label='Infectious'];
  Q[label='Isolated/quarantined'];
  H[label='Requires hospitalisation'];
  R[label='Recovered/immune'];
  F[label='Case fatality']

  # several 'edge' statements
  S->E
  I->S[style='dotted', label='act.rate.i\ninf.prob.i']
  E->I[label='prog.rate\nprog.dist.mu\nprog.dist.sigma']
  I->Q
  Q->S[style='dotted', label='act.rate.q\ninf.prob.q']
  I->R
  I->H
  H->F
  H->R
  Q->R
  Q->H
}
")
```
