---
title: "About this blog"
description: |
  _The lyf so short, the craft so long to lerne._<br>-- Geoffrey Chaucer, The Parliament of Birds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This is a blog dedicated to noodlings about health data science, mainly focussing on the use of `R`, but not exclusively. Posts are authored (unless otherwise indicated) by Tim Churches, who is a Senior Research Fellow at the [UNSW Medicine South Western Sydney Clinical School](https://swscs.med.unsw.edu.au) at [Liverpool Hospital](https://www.swslhd.health.nsw.gov.au/liverpool/), and a health data scientist at the [Ingham Institute for Applied Medical Research](https://inghaminstitute.org.au), also located at Liverpool, Sydney. He is also a visiting fellow at the [Centre for Big Data Research in Health](https://cbdrh.med.unsw.edu.au) in the Faculty of Medicine, UNSW Sydney, and helps teach and was a foundation convenor of the [MSc in Health Data Science course](https://cbdrh.med.unsw.edu.au/postgraduate-coursework) there. His background is in general medicine, general practice medicine, occupational health, public health practice, particularly population health surveillance, and clinical epidemiology.

Source code for posts to this blog is available from https://github.com/timchurches/blog under a [Creative Commons Attribution-ShareAlike International (CC BY-SA 4.0) license](https://creativecommons.org/licenses/by-sa/4.0/). Please observe the terms of this licence if you make any re-use of the code or content.
